package dryrun

const (
	CodeAddServers                                     = "AddServers"
	CodeAddVServerGroupBackendServers                  = "AddVServerGroupBackendServers"
	CodeAssociateAdditionalCertificatesWithListener    = "AssociateAdditionalCertificatesWithListener"
	CodeAttachCommonBandwidthPackage                   = "AttachCommonBandwidthPackage"
	CodeAuthorizeSecurityGroup                         = "AuthorizeSecurityGroup"
	CodeBatchWaitJobsFinish                            = "BatchWaitJobsFinish"
	CodeCreateDomainExtension                          = "CreateDomainExtension"
	CodeCreateListener                                 = "CreateListener"
	CodeCreateNLB                                      = "CreateNLB"
	CodeCreateSecurityGroup                            = "CreateSecurityGroup"
	CodeCreateServerGroup                              = "CreateServerGroup"
	CodeCreateSLB                                      = "CreateSLB"
	CodeCreateVgroup                                   = "CreateVgroup"
	CodeDeleteDomainExtension                          = "DeleteDomainExtension"
	CodeDeleteListener                                 = "DeleteListener"
	CodeDeleteNLB                                      = "DeleteNLB"
	CodeDeleteSecurityGroup                            = "DeleteSecurityGroup"
	CodeDeleteServerGroup                              = "DeleteServerGroup"
	CodeDeleteSLB                                      = "DeleteSLB"
	CodeDeleteVgroup                                   = "DeleteVgroup"
	CodeDetachCommonBandwidthPackage                   = "DetachCommonBandwidthPackage"
	CodeDisassociateAdditionalCertificatesWithListener = "DisassociateAdditionalCertificatesWithListener"
	CodeModifyInternetSpec                             = "ModifyInternetSpec"
	CodeModifyLoadBalancerInstanceChargeType           = "ModifyLoadBalancerInstanceChargeType"
	CodeModifySecurityGroupAttribute                   = "ModifySecurityGroupAttribute"
	CodeModifySecurityGroupRule                        = "ModifySecurityGroupRule"
	CodeModifySLBSpec                                  = "ModifySLBSpec"
	CodeModifyVgroup                                   = "ModifyVgroup"
	CodeRemoveServers                                  = "RemoveServers"
	CodeRemoveVgroup                                   = "RemoveVgroup"
	CodeRevokeSecurityGroup                            = "RevokeSecurityGroup"
	CodeSetDomainExtensionAttribute                    = "SetDomainExtensionAttribute"
	CodeSetSLBDeleteProtection                         = "SetSLBDeleteProtection"
	CodeSetSLBModificationProtection                   = "SetSLBModificationProtection"
	CodeSetSLBName                                     = "SetSLBName"
	CodeStartListener                                  = "StartListener"
	CodeStopListener                                   = "StopListener"
	CodeTagResource                                    = "TagResource"
	CodeTagSLB                                         = "TagSLB"
	CodeUntagResources                                 = "UntagResources"
	CodeUntagSLB                                       = "UntagSLB"
	CodeUpdateAddressType                              = "UpdateAddressType"
	CodeUpdateIPv6AddressType                          = "UpdateIPv6AddressType"
	CodeUpdateListener                                 = "UpdateListener"
	CodeUpdateLoadBalancerProtection                   = "UpdateLoadBalancerProtection"
	CodeUpdateNLB                                      = "UpdateNLB"
	CodeUpdateSecurityGroupIds                         = "UpdateSecurityGroupIds"
	CodeUpdateServerGroup                              = "UpdateServerGroup"
	CodeUpdateServers                                  = "UpdateServers"
	CodeUpdateZones                                    = "UpdateZones"
	CodeWaitJobFinish                                  = "WaitJobFinish"
)

const (
	MTypeUntagResources = "UntagResources"
)
