apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: metaserver
  labels:
    app: metaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metaserver
  template:
    metadata:
      labels:
        app: metaserver
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      containers:
        - name: nginx-net
          image: registry.cn-hangzhou.aliyuncs.com/spacexnice/nginx-net:latest